///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FavoritePlaces {
/*
{
  "id": 2,
  "name": "Windsor Palace Luxury Heritage Hotel Since 1902 by Paradise Inn Group",
  "address": "Alexandria",
  "type": "App\\Models\\Hotel",
  "img_url": [
    "https://content.r9cdn.net/rimg/himg/ef/0c/ec/expediav2-154845-3036623588-717875.jpg?width=452&height=400&xhint=540&yhint=333&crop=true&watermarkheight=28&watermarkpadding=10"
  ]
}
*/

  int? id;
  String? name;
  String? address;
  String? type;
  List<String?>? imgUrl;

  FavoritePlaces({
    this.id,
    this.name,
    this.address,
    this.type,
    this.imgUrl,
  });
  FavoritePlaces.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    address = json['address']?.toString();
    type = json['type']?.toString();
    if (json['img_url'] != null) {
      final v = json['img_url'];
      final arr0 = <String>[];
      v.forEach((v) {
        arr0.add(v.toString());
      });
      imgUrl = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['address'] = address;
    data['type'] = type;
    if (imgUrl != null) {
      final v = imgUrl;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v);
      });
      data['img_url'] = arr0;
    }
    return data;
  }
}
