name: graduation_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter_svprogresshud: ^1.0.1

  flutter_localization: ^0.2.0


  flutter:
    sdk: flutter

  # Responsive UI
  flutter_screenutil: ^5.9.0
  # Icons
  font_awesome_flutter: ^10.7.0
  # Local DB
  shared_preferences: ^2.2.0
  #Pro
  provider: ^6.0.5

  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  im_stepper: ^1.0.1+1
  easy_stepper: ^0.8.3
  dotted_border: ^2.1.0
  flutter_bloc: ^8.1.5
  dio: ^5.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:

    - assets/images/
    - assets/translation/ar.json
    - assets/translation/en.json
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf




  uses-material-design: true

