name: epic_expolre
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Responsive UI
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  dio: ^5.4.1
  bloc: ^8.1.3
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  flutter_bloc: ^8.1.4
  cupertino_icons: ^1.0.2
  jwt_decoder: ^2.0.1
  dropdown_button2: ^2.3.9
  im_stepper: ^1.0.1+1
  easy_stepper: ^0.8.3
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf




  uses-material-design: true

