name: graduation_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Responsive UI
  flutter_screenutil: ^5.9.0
  # Icons
  font_awesome_flutter: ^10.5.0
  # Local DB
  shared_preferences: ^2.2.0
  #Pro
  provider: ^6.0.5

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/logo.png


  uses-material-design: true

